// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    name
) VALUES (
    $1, $2
) RETURNING name
`

type CreateAccountParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.ID, arg.Name)
	var name string
	err := row.Scan(&name)
	return name, err
}
