// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    status
) VALUES (
    $1, $2
) RETURNING id
`

type CreateAccountParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Status)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
