// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name,
    status
) VALUES (
    $1, $2
) RETURNING name
`

type CreateAccountParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Status)
	var name string
	err := row.Scan(&name)
	return name, err
}
