// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Account struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

type Payment struct {
	ID          int32     `json:"id"`
	AccountName string    `json:"account_name"`
	Name        string    `json:"name"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Product struct {
	ID          int32     `json:"id"`
	AccountName string    `json:"account_name"`
	Name        string    `json:"name"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID          int32     `json:"id"`
	AccountName string    `json:"account_name"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Rol         string    `json:"rol"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
