// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order_line.sql

package db

import (
	"context"
)

const createOrderLine = `-- name: CreateOrderLine :exec
INSERT INTO order_lines (
    account_name,
    sale_order_id,
    ammount,
    product_id
) VALUES (
    $1, $2, $3, $4
)
`

type CreateOrderLineParams struct {
	AccountName string `json:"account_name"`
	SaleOrderID int32  `json:"sale_order_id"`
	Ammount     int32  `json:"ammount"`
	ProductID   int32  `json:"product_id"`
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) error {
	_, err := q.db.ExecContext(ctx, createOrderLine,
		arg.AccountName,
		arg.SaleOrderID,
		arg.Ammount,
		arg.ProductID,
	)
	return err
}
