// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sale_order.sql

package db

import (
	"context"
)

const createSaleOrder = `-- name: CreateSaleOrder :one
INSERT INTO sale_orders (
    account_name,
    user_id,
    payment_id
) VALUES (
    $1, $2, $3
) RETURNING id
`

type CreateSaleOrderParams struct {
	AccountName string `json:"account_name"`
	UserID      int32  `json:"user_id"`
	PaymentID   int32  `json:"payment_id"`
}

func (q *Queries) CreateSaleOrder(ctx context.Context, arg CreateSaleOrderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createSaleOrder, arg.AccountName, arg.UserID, arg.PaymentID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
